name: advanced2
channels:
  - conda-forge
dependencies:
  - folium=0.11*
  - jinja2=2.10*
  - osmnx=0.15*
  - matplotlib
  - pandas=1.0*
  - geopandas=0.80*
  - descartes
  - shapely
  - poppler
  - numpy
  - scipy
